export const _suppliers = [
  {
    id: 1,
    name: "2W Energia",
    logo: "/2w-energia-logo.png",
    state: "São Paulo",
    costPerKwh: 0.45,
    minKwh: 2000,
    totalClients: 1500,
    avgRating: 4.4,
  },
  {
    id: 2,
    name: "Abengoa",
    logo: "/abengoa-logo.png",
    state: "Rio de Janeiro",
    costPerKwh: 0.48,
    minKwh: 2500,
    totalClients: 1200,
    avgRating: 4.2,
  },
  {
    id: 3,
    name: "AES Brasil",
    logo: "/aes-brasil-logo.png",
    state: "São Paulo",
    costPerKwh: 0.47,
    minKwh: 2200,
    totalClients: 1300,
    avgRating: 4.3,
  },
  {
    id: 4,
    name: "Casa dos Ventos",
    logo: "/casa-dos-ventos-logo.png",
    state: "Ceará",
    costPerKwh: 0.44,
    minKwh: 2300,
    totalClients: 1100,
    avgRating: 4.5,
  },
  {
    id: 5,
    name: "Eneva",
    logo: "/eneva-logo.png",
    state: "Maranhão",
    costPerKwh: 0.46,
    minKwh: 2400,
    totalClients: 1000,
    avgRating: 4.0,
  },
  {
    id: 6,
    name: "Engie Brasil",
    logo: "/engie-brasil-logo.png",
    state: "Santa Catarina",
    costPerKwh: 0.49,
    minKwh: 2100,
    totalClients: 1600,
    avgRating: 4.6,
  },
  {
    id: 7,
    name: "Enel Green Power",
    logo: "/enel-green-power-logo.png",
    state: "São Paulo",
    costPerKwh: 0.47,
    minKwh: 2200,
    totalClients: 1700,
    avgRating: 4.4,
  },
  {
    id: 8,
    name: "Iberdrola Renováveis Brasil",
    logo: "/iberdrola-logo.png",
    state: "Bahia",
    costPerKwh: 0.43,
    minKwh: 2000,
    totalClients: 1800,
    avgRating: 4.7,
  },
  {
    id: 9,
    name: "Omega Energia",
    logo: "/omega-energia-logo.png",
    state: "Minas Gerais",
    costPerKwh: 0.42,
    minKwh: 2300,
    totalClients: 1900,
    avgRating: 4.3,
  },
  {
    id: 10,
    name: "EDP Renováveis Brasil",
    logo: "/edp-renovaveis-logo.png",
    state: "Espírito Santo",
    costPerKwh: 0.45,
    minKwh: 2100,
    totalClients: 1400,
    avgRating: 4.5,
  },
  {
    id: 11,
    name: "CPFL Renováveis",
    logo: "/cpfl-renovaveis-logo.png",
    state: "São Paulo",
    costPerKwh: 0.5,
    minKwh: 2500,
    totalClients: 1600,
    avgRating: 4.4,
  },
  {
    id: 12,
    name: "Renova Energia",
    logo: "/renova-energia-logo.png",
    state: "Minas Gerais",
    costPerKwh: 0.48,
    minKwh: 2200,
    totalClients: 1300,
    avgRating: 4.3,
  },
  {
    id: 13,
    name: "Solatio Energia",
    logo: "/solatio-energia-logo.png",
    state: "Pernambuco",
    costPerKwh: 0.43,
    minKwh: 2400,
    totalClients: 1500,
    avgRating: 4.5,
  },
  {
    id: 14,
    name: "Blue Sol Energia Solar",
    logo: "/blue-sol-logo.png",
    state: "São Paulo",
    costPerKwh: 0.45,
    minKwh: 2200,
    totalClients: 1100,
    avgRating: 4.2,
  },
  {
    id: 15,
    name: "Ventos do Sul",
    logo: "/ventos-do-sul-logo.png",
    state: "Rio Grande do Sul",
    costPerKwh: 0.46,
    minKwh: 2100,
    totalClients: 1200,
    avgRating: 4.6,
  },
  {
    id: 16,
    name: "Cemig",
    logo: "/cemig-logo.png",
    state: "Minas Gerais",
    costPerKwh: 0.47,
    minKwh: 2300,
    totalClients: 1700,
    avgRating: 4.3,
  },
  {
    id: 17,
    name: "Alupar",
    logo: "/alupar-logo.png",
    state: "São Paulo",
    costPerKwh: 0.44,
    minKwh: 2000,
    totalClients: 1800,
    avgRating: 4.5,
  },
  {
    id: 18,
    name: "Neonergia",
    logo: "/neonergia-logo.png",
    state: "Bahia",
    costPerKwh: 0.42,
    minKwh: 2400,
    totalClients: 1500,
    avgRating: 4.4,
  },
  {
    id: 19,
    name: "Volta Energia",
    logo: "/volta-energia-logo.png",
    state: "Rio de Janeiro",
    costPerKwh: 0.41,
    minKwh: 2500,
    totalClients: 1600,
    avgRating: 4.2,
  },
  {
    id: 20,
    name: "Canadian Solar",
    logo: "/canadian-solar-logo.png",
    state: "São Paulo",
    costPerKwh: 0.48,
    minKwh: 2100,
    totalClients: 1400,
    avgRating: 4.3,
  },
];
